/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_flexio_i2c_master.h"
#include "fsl_lpi2c.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Definition of peripheral ID */
#define FLEXIO0_PERIPHERAL FLEXIO0
/* Definition of the clock source frequency */
#define FLEXIO0_CLK_FREQ 150000000UL
/* BOARD_InitPeripherals defines for LP_FLEXCOMM4 */
/* Definition of peripheral ID */
#define LP_FLEXCOMM4_PERIPHERAL LPI2C4
/* Definition of peripheral base address */
#define LP_FLEXCOMM4_PERIPHERAL_BASE LPI2C4_BASE
/* Definition of the clock source frequency */
#define LP_FLEXCOMM4_CLOCK_SOURCE 75000000UL

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
/* FlexIO peripheral configuration */
extern FLEXIO_I2C_Type FLEXIO0_peripheralConfig;
/* FlexIO I2C master configuration */
extern flexio_i2c_master_config_t FLEXIO0_config;
extern const lpi2c_master_config_t LP_FLEXCOMM4_masterConfig;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
